#!/bin/sh

set -e
set -x

cd $(dirname $0)

test -d repo

. ../variables

export http_proxy=http://localhost:55555
export https_proxy=http://localhost:8081
export SOCKS_SERVER=localhost:9050
export PYTHONPATH=$HOME/code/fdroid/fdroidserver

chmod 0600 config.yml

# delete any corrupt APKs
for f in */*.apk; do unzip -l "$f" > /dev/null || rm $f; done

# get map files and create metadata for any new ones
scripts/download-osmand-map-files.py
# update APKs and delete any unknown ones, make index
scripts/fdroid-update-ersatz.py
~/code/fdroid/fdroidserver/fdroid signindex --verbose

export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
~/code/fdroid/fdroidserver/fdroid deploy -v

scripts/update-repo-zipball.py

